CREATE TABLE IF NOT EXISTS semester_assessment (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Sid VARCHAR(50) NOT NULL,
    Course_Code VARCHAR(50) NOT NULL,
    A1 DECIMAL(6,2) NULL,
    A2 DECIMAL(6,2) NULL,
    A3 DECIMAL(6,2) NULL,
    T1 DECIMAL(6,2) NULL,
    T2 DECIMAL(6,2) NULL,
    Exam DECIMAL(6,2) NULL,
    Total_CA DECIMAL(6,2) NULL,
    semester VARCHAR(20) NOT NULL,
    Year VARCHAR(10) NOT NULL,
    program_type VARCHAR(20) NOT NULL DEFAULT 'semester',
    posted_by VARCHAR(50) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_semester_assessment_student_course_period (Sid, Course_Code, semester, Year),
    INDEX idx_semester_assessment_period (semester, Year)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS portal_settings (
    setting_key VARCHAR(64) PRIMARY KEY,
    setting_value VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE course_registration
    ADD COLUMN IF NOT EXISTS tuition_total DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN IF NOT EXISTS amount_paid DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN IF NOT EXISTS is_active TINYINT(1) NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP;
