<?php
declare(strict_types=1);
$page_title='AI Teaching Assistant';
require_once __DIR__.'/includes/guard.php';
require_once dirname(__DIR__).'/includes/helpers/lecturer_course_helpers.php';
require_once dirname(__DIR__).'/services/support/SupportCaseService.php';
require_once __DIR__.'/includes/nav.php';
$staffId=(string)$_SESSION['staff_id'];
$courses=wuc_lecturer_resolved_course_codes($db,$staffId);
$support=new SupportCaseService($db);
$cases=$support->staffCases($staffId,'lecturer');
$answers=[];$verified=[];$common=[];$settings=[];
if($courses){$ph=implode(',',array_fill(0,count($courses),'?'));$types=str_repeat('s',count($courses));
 $stmt=$db->prepare("SELECT m.id,m.content,m.content_status,m.created_at,c.course_id,c.student_id,(SELECT content FROM ai_messages q WHERE q.conversation_id=m.conversation_id AND q.sender_role='student' AND q.id<m.id ORDER BY q.id DESC LIMIT 1) question FROM ai_messages m INNER JOIN ai_conversations c ON c.id=m.conversation_id WHERE m.sender_role='assistant' AND m.content_status IN ('draft','reviewed') AND c.course_id IN ($ph) ORDER BY m.created_at DESC LIMIT 50");$stmt->bind_param($types,...$courses);$stmt->execute();$answers=$stmt->get_result()->fetch_all(MYSQLI_ASSOC);$stmt->close();
 $stmt=$db->prepare("SELECT id,course_id,topic,question,answer,status,verified_at,use_count FROM verified_answers WHERE course_id IN ($ph) ORDER BY verified_at DESC LIMIT 50");$stmt->bind_param($types,...$courses);$stmt->execute();$verified=$stmt->get_result()->fetch_all(MYSQLI_ASSOC);$stmt->close();
 $stmt=$db->prepare("SELECT c.course_id,m.question_hash,MIN(m.content) question,COUNT(*) total FROM ai_messages m INNER JOIN ai_conversations c ON c.id=m.conversation_id WHERE m.sender_role='student' AND m.question_hash IS NOT NULL AND c.course_id IN ($ph) GROUP BY c.course_id,m.question_hash HAVING COUNT(*)>1 ORDER BY total DESC LIMIT 20");$stmt->bind_param($types,...$courses);$stmt->execute();$common=$stmt->get_result()->fetch_all(MYSQLI_ASSOC);$stmt->close();
 $stmt=$db->prepare("SELECT course_id,is_enabled,default_ai_mode FROM ai_course_settings WHERE course_id IN ($ph)");$stmt->bind_param($types,...$courses);$stmt->execute();foreach($stmt->get_result()->fetch_all(MYSQLI_ASSOC) as $s){$settings[$s['course_id']]=$s;}$stmt->close();}
$csrf=(string)$_SESSION['csrf_token'];
?>
<link rel="stylesheet" href="/wucportal/css/ai-learning.css?v=20260718">
<main class="main-content ai-page">
<section class="ai-hero"><h1><i class="fas fa-wand-magic-sparkles me-2"></i>AI Teaching Assistant</h1><p>Review learner support requests, verify AI drafts, reuse approved answers, and control course AI modes.</p></section>
<div class="row g-3 mb-4"><div class="col-md-3"><div class="ai-card h-100 mb-0"><div class="ai-card-body"><div class="text-muted small">Open support</div><div class="fs-2 fw-bold"><?=count(array_filter($cases,fn($c)=>!in_array($c['status'],['resolved','closed'],true)))?></div></div></div></div><div class="col-md-3"><div class="ai-card h-100 mb-0"><div class="ai-card-body"><div class="text-muted small">Awaiting review</div><div class="fs-2 fw-bold"><?=count($answers)?></div></div></div></div><div class="col-md-3"><div class="ai-card h-100 mb-0"><div class="ai-card-body"><div class="text-muted small">Verified answers</div><div class="fs-2 fw-bold"><?=count($verified)?></div></div></div></div><div class="col-md-3"><div class="ai-card h-100 mb-0"><div class="ai-card-body"><div class="text-muted small">Assigned courses</div><div class="fs-2 fw-bold"><?=count($courses)?></div></div></div></div></div>

<article class="ai-card"><div class="ai-card-header"><h2><i class="fas fa-headset me-2 text-primary"></i>Learner support queue</h2><span class="badge bg-primary"><?=count($cases)?></span></div><div class="ai-card-body"><?php if(!$cases):?><div class="text-center text-muted py-4"><i class="fas fa-inbox fa-2x"></i><p>No support requests assigned to you.</p></div><?php else:foreach($cases as $case):$caseSources=json_decode((string)($case['sources_used']??'[]'),true);if(!is_array($caseSources))$caseSources=[];?><div class="ai-case" id="case-<?= (int)$case['id'] ?>"><div class="d-flex flex-wrap justify-content-between gap-2"><div><strong>#<?=(int)$case['id']?> · <?=htmlspecialchars((string)$case['course_id'])?></strong><div class="ai-case-meta">Student <?=htmlspecialchars((string)$case['student_id'])?> · Period <?=htmlspecialchars((string)($case['academic_period_id']??'Not resolved'))?> · Due <?=htmlspecialchars((string)$case['due_at'])?></div></div><span class="ai-status <?=htmlspecialchars((string)$case['status'])?>"><?=htmlspecialchars(str_replace('_',' ',(string)$case['status']))?></span></div><details class="mt-3"><summary class="fw-semibold">Complete learner context</summary><p class="mt-2 mb-1"><strong>Question:</strong> <?=nl2br(htmlspecialchars((string)$case['original_question']))?></p><p><strong>Student attempt:</strong><br><?=nl2br(htmlspecialchars((string)($case['student_attempt']?:'No attempt supplied.')))?></p><div class="alert alert-light border"><strong>AI draft:</strong><br><?=nl2br(htmlspecialchars((string)$case['ai_response']))?></div><strong>Sources:</strong><?php if(!$caseSources):?><span class="text-muted"> No approved sources recorded.</span><?php else:?><ul class="mb-0"><?php foreach($caseSources as $source):?><li><?=htmlspecialchars((string)($source['title']??'Course source'))?> <small class="text-muted">(<?=htmlspecialchars((string)($source['verification_status']??'unverified'))?>)</small></li><?php endforeach;?></ul><?php endif;?></details><?php if(!in_array($case['status'],['resolved','closed'],true)):?><textarea class="form-control mt-3" rows="3" data-case-response="<?=(int)$case['id']?>" placeholder="Write a human response…"></textarea><button class="btn btn-ai btn-sm mt-2" data-respond-case="<?=(int)$case['id']?>"><i class="fas fa-reply me-1"></i>Send response</button><?php endif;?></div><?php endforeach;endif;?></div></article>

<div class="ai-grid"><section><article class="ai-card"><div class="ai-card-header"><h2><i class="fas fa-clipboard-check me-2 text-primary"></i>AI answers awaiting review</h2><span class="badge bg-warning text-dark"><?=count($answers)?></span></div><div class="ai-card-body"><?php if(!$answers):?><div class="text-center text-muted py-4">No AI drafts are awaiting review.</div><?php else:foreach($answers as $item):?><div class="ai-case" id="answer-<?=(int)$item['id']?>"><div class="d-flex justify-content-between"><strong><?=htmlspecialchars((string)$item['course_id'])?></strong><span class="ai-status <?=htmlspecialchars((string)$item['content_status'])?>"><?=htmlspecialchars((string)$item['content_status'])?></span></div><p class="mt-2 mb-1"><strong>Learner:</strong> <?=htmlspecialchars((string)$item['question'])?></p><div class="alert alert-light border"><?=nl2br(htmlspecialchars((string)$item['content']))?></div><input class="form-control form-control-sm mb-2" data-topic="<?=(int)$item['id']?>" placeholder="Topic (optional)"><div class="d-flex flex-wrap gap-2"><button class="btn btn-sm btn-outline-secondary" data-review="reviewed" data-message="<?=(int)$item['id']?>">Mark reviewed</button><button class="btn btn-sm btn-outline-danger" data-review="rejected" data-message="<?=(int)$item['id']?>">Reject</button><button class="btn btn-sm btn-success" data-review="approved" data-message="<?=(int)$item['id']?>">Approve & verify</button><button class="btn btn-sm btn-ai" data-review="published" data-message="<?=(int)$item['id']?>">Publish</button></div></div><?php endforeach;endif;?></div></article></section>
<aside><article class="ai-card"><div class="ai-card-header"><h3><i class="fas fa-sliders me-2 text-primary"></i>Course AI settings</h3></div><div class="ai-card-body"><?php if(!$courses):?><p class="text-muted">No assigned courses.</p><?php else:foreach($courses as $code):$mode=$settings[$code]['default_ai_mode']??'full_tutoring';?><form class="ai-setting-form border-bottom pb-3 mb-3"><input type="hidden" name="course_id" value="<?=htmlspecialchars($code)?>"><label class="form-label fw-semibold"><?=htmlspecialchars($code)?></label><select class="form-select form-select-sm" name="ai_mode"><?php foreach(['full_tutoring','hints_only','concepts_and_examples','practice_only','disabled'] as $m):?><option value="<?=$m?>" <?=$m===$mode?'selected':''?>><?=htmlspecialchars(str_replace('_',' ',$m))?></option><?php endforeach;?></select><input class="form-control form-control-sm mt-2" name="assessment_id" placeholder="Assessment ID (optional)"><button class="btn btn-sm btn-outline-primary mt-2">Save mode</button></form><?php endforeach;endif;?></div></article>
<article class="ai-card"><div class="ai-card-header"><h3><i class="fas fa-circle-question me-2 text-primary"></i>Common questions</h3></div><div class="ai-card-body"><?php if(!$common):?><p class="text-muted mb-0">No repeated questions yet.</p><?php else:foreach($common as $q):?><div class="ai-case"><strong><?=htmlspecialchars((string)$q['course_id'])?> · <?= (int)$q['total'] ?> times</strong><div><?=htmlspecialchars(mb_substr((string)$q['question'],0,180))?></div></div><?php endforeach;endif;?></div></article></aside></div>
<article class="ai-card"><div class="ai-card-header"><h2><i class="fas fa-badge-check me-2 text-primary"></i>Verified answers</h2></div><div class="ai-card-body"><div class="table-responsive"><table class="table ai-table"><thead><tr><th>Course</th><th>Question / topic</th><th>Status</th><th>Reuse</th></tr></thead><tbody><?php if(!$verified):?><tr><td colspan="4" class="text-center text-muted">No verified answers yet.</td></tr><?php else:foreach($verified as $v):?><tr><td><?=htmlspecialchars((string)$v['course_id'])?></td><td><strong><?=htmlspecialchars((string)($v['topic']?:'Verified answer'))?></strong><br><small><?=htmlspecialchars(mb_substr((string)$v['question'],0,180))?></small></td><td><span class="ai-status <?=htmlspecialchars((string)$v['status'])?>"><?=htmlspecialchars((string)$v['status'])?></span></td><td><?= (int)$v['use_count'] ?></td></tr><?php endforeach;endif;?></tbody></table></div></div></article>
</main>
<script>window.WUC_AI={csrf:<?=json_encode($csrf)?>};</script><script src="/wucportal/lecturers/js/ai-teaching-assistant.js?v=20260718"></script>
