<?php
/**
 * admin/update_student_program.php
 *
 * Admin tool: update a student's enrolled program.
 *
 * POST fields expected:
 *   student_id      – the student's SID
 *   new_program_id  – the target program_code
 *   csrf_token      – CSRF token (generated by App\Csrf::field())
 *
 * Access control: systems_admin
 * CSRF protection: App\Csrf::verify()
 * Flash messages:  $_SESSION['flash'] ['type'] / ['message']
 * Change logging:  audit_log() from includes/audit.php
 */

// ── Bootstrap ────────────────────────────────────────────────────────────────
require_once __DIR__ . '/../db/connect.php';           // provides $db (mysqli)
require_once __DIR__ . '/../app/autoload.php';          // App\ namespace autoloader
require_once __DIR__ . '/../includes/role_helpers.php'; // hasAnyRole(), requireRole()
require_once __DIR__ . '/../includes/audit.php';        // audit_log_current_user()
require_once __DIR__ . '/../includes/helpers/academic_structure_helpers.php';
require_once __DIR__ . '/../includes/cse_progression.php';

if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// ── Auth guard ───────────────────────────────────────────────────────────────
// Unauthorized = a logged-in staff member who is not registrar/systems_admin,
// so bounce to the staff hub (absolute), not the student portal ('../index.php').
requireRole([ROLE_SYSTEMS_ADMIN], '/wucportal/portal_selection.php');

// ── Constants ────────────────────────────────────────────────────────────────
const SELF_URL = 'update_student_program.php';

// ── Handle POST ──────────────────────────────────────────────────────────────
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // 1. CSRF verification (redirects + exits on failure)
    \App\Csrf::verify(SELF_URL);

    // 2. Presence validation
    $studentId    = trim($_POST['student_id']     ?? '');
    $newProgramId = trim($_POST['new_program_id'] ?? '');

    $errors = [];

    if ($studentId === '') {
        $errors[] = 'Student ID is required.';
    }
    if ($newProgramId === '') {
        $errors[] = 'New program is required.';
    }

    if (!empty($errors)) {
        $_SESSION['flash'] = [
            'type'    => 'danger',
            'message' => implode(' ', $errors),
        ];
        header('Location: ' . SELF_URL);
        exit;
    }

    // 3. Check student exists in students table
    $stmt = $db->prepare("SELECT SID FROM students WHERE SID = ? LIMIT 1");
    if (!$stmt) {
        error_log('[UpdateStudentProgram] Prepare failed: ' . $db->error);
        $_SESSION['flash'] = [
            'type'    => 'danger',
            'message' => 'A database error occurred. Please try again.',
        ];
        header('Location: ' . SELF_URL);
        exit;
    }
    $stmt->bind_param('s', $studentId);
    $stmt->execute();
    $stmt->store_result();
    $studentExists = $stmt->num_rows > 0;
    $stmt->close();

    if (!$studentExists) {
        $_SESSION['flash'] = [
            'type'    => 'warning',
            'message' => 'Student ID "' . htmlspecialchars($studentId, ENT_QUOTES, 'UTF-8') . '" was not found in the system.',
        ];
        header('Location: ' . SELF_URL);
        exit;
    }

    // 4. Check program exists in programs table
    $stmt = $db->prepare("SELECT program_code FROM programs WHERE program_code = ? LIMIT 1");
    if (!$stmt) {
        error_log('[UpdateStudentProgram] Prepare failed: ' . $db->error);
        $_SESSION['flash'] = [
            'type'    => 'danger',
            'message' => 'A database error occurred. Please try again.',
        ];
        header('Location: ' . SELF_URL);
        exit;
    }
    $stmt->bind_param('s', $newProgramId);
    $stmt->execute();
    $stmt->store_result();
    $programExists = $stmt->num_rows > 0;
    $stmt->close();

    if (!$programExists) {
        $_SESSION['flash'] = [
            'type'    => 'warning',
            'message' => 'Program code "' . htmlspecialchars($newProgramId, ENT_QUOTES, 'UTF-8') . '" does not exist.',
        ];
        header('Location: ' . SELF_URL);
        exit;
    }

    if ($stageError = wuc_cse_direct_assignment_error($newProgramId)) {
        $_SESSION['flash'] = ['type' => 'warning', 'message' => $stageError];
        header('Location: ' . SELF_URL);
        exit;
    }

    // 5. Fetch the student's current program for audit trail
    $oldProgramId = null;
    $oldProgramRow = [];
    $stmt = $db->prepare("SELECT id, program_code, term, semester, current_term_number, current_semester_number, current_level_number, intake FROM student_program WHERE Sid = ? ORDER BY id DESC LIMIT 1");
    if ($stmt) {
        $stmt->bind_param('s', $studentId);
        $stmt->execute();
        $result = $stmt->get_result();
        if ($row = $result->fetch_assoc()) {
            $oldProgramId = $row['program_code'];
            $oldProgramRow = $row;
        }
        $stmt->close();
    }

    $periodSource = array_merge($oldProgramRow, $_POST);
    $periodPayload = wuc_student_program_period_payload($db, $newProgramId, wuc_student_program_period_input($db, $newProgramId, $periodSource, 1));
    if (!$periodPayload['ok']) {
        $_SESSION['flash'] = [
            'type'    => 'danger',
            'message' => $periodPayload['reason'],
        ];
        header('Location: ' . SELF_URL);
        exit;
    }
    $periodFields = $periodPayload['fields'];

    if ($newProgramId === $oldProgramId) {
        $_SESSION['flash'] = [
            'type'    => 'info',
            'message' => 'Student is already enrolled in program "' . htmlspecialchars($newProgramId, ENT_QUOTES, 'UTF-8') . '".',
        ];
        header('Location: ' . SELF_URL);
        exit;
    }

    $activeDupStmt = $db->prepare("SELECT id FROM student_program WHERE Sid = ? AND program_code = ? AND LOWER(COALESCE(status, 'active')) = 'active' LIMIT 1");
    if ($activeDupStmt) {
        $activeDupStmt->bind_param('ss', $studentId, $newProgramId);
        $activeDupStmt->execute();
        if ($activeDupStmt->get_result()->num_rows > 0) {
            $activeDupStmt->close();
            $_SESSION['flash'] = [
                'type'    => 'warning',
                'message' => 'Student already has an active enrolment in program "' . htmlspecialchars($newProgramId, ENT_QUOTES, 'UTF-8') . '".',
            ];
            header('Location: ' . SELF_URL);
            exit;
        }
        $activeDupStmt->close();
    }

    $spRowId = isset($oldProgramRow['id']) ? (int)$oldProgramRow['id'] : 0;

    // 6. Update student_program table
    try {
        if ($spRowId > 0) {
            // Row exists — update the specific enrolment row only
            $stmt = $db->prepare(
                "UPDATE student_program
                    SET program_code = ?,
                        term = ?,
                        semester = ?,
                        current_term_number = ?,
                        current_semester_number = ?,
                        current_level_number = ?
                  WHERE id = ? AND Sid = ?"
            );
            if (!$stmt) {
                throw new RuntimeException('Prepare failed: ' . $db->error);
            }
            $stmt->bind_param('ssssssis', $newProgramId, $periodFields['term'], $periodFields['semester'], $periodFields['current_term_number'], $periodFields['current_semester_number'], $periodFields['current_level_number'], $spRowId, $studentId);
        } else {
            // No existing program row — insert a new one
            $stmt = $db->prepare(
                "INSERT INTO student_program
                    (Sid, program_code, term, semester, current_term_number, current_semester_number, current_level_number, status, registration_date)
                 VALUES (?, ?, ?, ?, ?, ?, ?, 'active', CURDATE())"
            );
            if (!$stmt) {
                throw new RuntimeException('Prepare failed: ' . $db->error);
            }
            $stmt->bind_param('sssssss', $studentId, $newProgramId, $periodFields['term'], $periodFields['semester'], $periodFields['current_term_number'], $periodFields['current_semester_number'], $periodFields['current_level_number']);
        }

        if (!$stmt->execute()) {
            throw new RuntimeException('Execute failed: ' . $stmt->error);
        }
        $stmt->close();

    } catch (RuntimeException $e) {
        error_log('[UpdateStudentProgram] DB error: ' . $e->getMessage());
        $_SESSION['flash'] = [
            'type'    => 'danger',
            'message' => 'Failed to update student program due to a database error. Please try again.',
        ];
        header('Location: ' . SELF_URL);
        exit;
    }

    // 7. Audit log
    audit_log_current_user($db, 'student.program.updated', [
        'student_id'     => $studentId,
        'old_program_id' => $oldProgramId ?? 'none',
        'new_program_id' => $newProgramId,
    ]);

    // 8. Success flash + redirect (PRG pattern)
    $_SESSION['flash'] = [
        'type'    => 'success',
        'message' => 'Program updated successfully for student '
                   . htmlspecialchars($studentId, ENT_QUOTES, 'UTF-8') . '.',
    ];
    header('Location: ' . SELF_URL);
    exit;
}

// ── GET: load programs list for dropdown ─────────────────────────────────────
$programs = [];
$programsResult = $db->query(
    "SELECT program_code, program_name
       FROM programs
      WHERE COALESCE(is_active, 1) = 1
        AND program_code NOT IN ('CSE', 'ICT-002')
      ORDER BY program_name ASC"
);
if ($programsResult) {
    while ($row = $programsResult->fetch_assoc()) {
        $programs[] = $row;
    }
}

// ── Consume and clear flash message ──────────────────────────────────────────
$flash = $_SESSION['flash'] ?? null;
unset($_SESSION['flash']);
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Update Student Program | ITC Portal</title>
    <link rel="icon" href="/wucportal/images/favicon.ico" sizes="any">
    <link rel="icon" type="image/png" sizes="32x32" href="/wucportal/images/favicon-32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/wucportal/images/favicon-16.png">
    <link rel="apple-touch-icon" href="/wucportal/images/apple-touch-icon.png">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" href="/wucportal/css/admin-style.css">
    <link rel="stylesheet" href="/wucportal/css/portal-dashboard.css">
</head>
<body class="bg-light">

    <?php require_once __DIR__ . '/includes/navbar.php'; ?>

    <div class="content-wrapper">
        <div class="container-fluid px-4 py-4">

            <!-- Page header -->
            <div class="d-flex justify-content-between align-items-center mb-4">
                <div>
                    <h3 class="mb-1">
                        <i class="fas fa-user-graduate me-2"></i>Update Student Program
                    </h3>
                    <p class="text-muted mb-0">
                        Reassign a student to a different academic program.
                    </p>
                </div>
                <a href="students_by_admin.php" class="btn btn-outline-secondary">
                    <i class="fas fa-arrow-left me-1"></i>Back to Students
                </a>
            </div>

            <!-- Flash message -->
            <?php if ($flash): ?>
                <div class="alert alert-<?php echo htmlspecialchars($flash['type'], ENT_QUOTES, 'UTF-8'); ?> alert-dismissible fade show" role="alert">
                    <?php if ($flash['type'] === 'success'): ?>
                        <i class="fas fa-check-circle me-2"></i>
                    <?php elseif ($flash['type'] === 'warning'): ?>
                        <i class="fas fa-exclamation-triangle me-2"></i>
                    <?php else: ?>
                        <i class="fas fa-times-circle me-2"></i>
                    <?php endif; ?>
                    <?php echo htmlspecialchars($flash['message'], ENT_QUOTES, 'UTF-8'); ?>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            <?php endif; ?>

            <!-- Form card -->
            <div class="row justify-content-center">
                <div class="col-lg-6 col-md-8">
                    <div class="card shadow-sm">
                        <div class="card-header bg-white">
                            <h5 class="mb-0">
                                <i class="fas fa-edit me-2 text-primary"></i>Program Change Form
                            </h5>
                        </div>
                        <div class="card-body p-4">
                            <form method="POST" action="<?php echo SELF_URL; ?>" novalidate>
                                <?php \App\Csrf::field(); ?>

                                <!-- Student ID -->
                                <div class="mb-3">
                                    <label for="student_id" class="form-label fw-semibold">
                                        Student ID <span class="text-danger">*</span>
                                    </label>
                                    <input
                                        type="text"
                                        class="form-control"
                                        id="student_id"
                                        name="student_id"
                                        placeholder="e.g. 202100001"
                                        maxlength="20"
                                        required
                                        autocomplete="off"
                                        value="<?php echo htmlspecialchars($_POST['student_id'] ?? '', ENT_QUOTES, 'UTF-8'); ?>"
                                    >
                                    <div class="form-text">Enter the student's ID number exactly as it appears in the system.</div>
                                </div>

                                <!-- New Program -->
                                <div class="mb-4">
                                    <label for="new_program_id" class="form-label fw-semibold">
                                        New Program <span class="text-danger">*</span>
                                    </label>
                                    <select
                                        class="form-select"
                                        id="new_program_id"
                                        name="new_program_id"
                                        required
                                    >
                                        <option value="">-- Select a Program --</option>
                                        <?php foreach ($programs as $prog): ?>
                                            <option
                                                value="<?php echo htmlspecialchars($prog['program_code'], ENT_QUOTES, 'UTF-8'); ?>"
                                                <?php if (($_POST['new_program_id'] ?? '') === $prog['program_code']) echo 'selected'; ?>
                                            >
                                                <?php echo htmlspecialchars($prog['program_code'] . ' — ' . $prog['program_name'], ENT_QUOTES, 'UTF-8'); ?>
                                            </option>
                                        <?php endforeach; ?>
                                    </select>
                                    <div class="form-text">Select the program this student should be moved to.</div>
                                </div>

                                <!-- Submit -->
                                <div class="d-grid">
                                    <button type="submit" class="btn btn-primary btn-lg" id="submitBtn" disabled>
                                        <i class="fas fa-save me-2"></i>Update Program
                                    </button>
                                </div>
                            </form>
                        </div><!-- /.card-body -->
                    </div><!-- /.card -->
                </div>
            </div><!-- /.row -->

        </div><!-- /.container-fluid -->
    </div><!-- /.content-wrapper -->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        // Client-side guard: disable submit until both fields are filled
        (function () {
            const sidInput   = document.getElementById('student_id');
            const progSelect = document.getElementById('new_program_id');
            const submitBtn  = document.getElementById('submitBtn');

            function toggleSubmit() {
                submitBtn.disabled = (sidInput.value.trim() === '' || progSelect.value === '');
            }

            sidInput.addEventListener('input', toggleSubmit);
            progSelect.addEventListener('change', toggleSubmit);
            toggleSubmit(); // evaluate on load
        })();
    </script>
</body>
</html>
